### PR TITLE
replace nearly with parsimmon

### PR DESCRIPTION
**Pull request by andy128k**

### CODE REVIEW

**Comment by ljharb** [comment]
Can you elaborate on why this is a good change?

I’m concerned about doing such a major rewrite; especially since the repo has no CI.

**Comment by andy128k** [comment]
Nearly uses outdated dependency and author doesn't want to change it. Look at issue #12.

**Comment by ljharb** [comment]
I’m not sure a major rewrite is worth it just to avoid a logging warning - one that’s easy to ignore.

@aweary, thoughts?

**Comment by aweary** [comment]
Yeah, that's not sufficient IMO. @andy128k thanks for doing this, but I don't think we'll be making this change. I prefer to use the BMF grammar syntax that nearly provides and don't want to risk any breakage here.

**Pull request closed without merging**
